### ISSUE TITLE
Banner hide part of page.

### ISSUE THREAD

**Issue by zztalker** [cloudlinux/imunify360-doc#8]
When clicking on internal link (like https://docs.imunify360.com/command_line_interface/#get) part of information hidden under the top green banner. 
![image](https://user-images.githubusercontent.com/1027857/54755736-6d607c80-4c08-11e9-88c1-75a54ced6175.png)
Firefox/Chrome.
Awaited picture - when clicking on Get:
![image](https://user-images.githubusercontent.com/1027857/54756558-4dca5380-4c0a-11e9-80f1-a9ad391a980e.png)

**Comment by telepenin** [comment]
Fixed.
